site_name: {{ cookiecutter.project_name }}
site_author: {{ cookiecutter.full_name }}
site_description: {{ cookiecutter.project_short_description }} 
site_favicon: favicon.ico

repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}
edit_uri: edit/master/docs/docs
copyright: Copyright &copy; <a target=_blanks href="https://www.github.com/{{ cookiecutter.github_username }}">{{ cookiecutter.full_name }}</a>

theme:
  name: shadocs
  logo: '/images/logo.png'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: cn
  highlightjs: true
  hljs_languages:
    - python 
    - javascript
    - shell
    - django
  

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{ cookiecutter.github_username }}
      name: {{ cookiecutter.github_username }} 

markdown_extensions:
  - admonition
  - toc:
      toc_depth: 2
      permalink: True

# Page tree
nav:
  - index: index.md
  - version: version.md