[project]
authors = ["{{cookiecutter.full_name}}<{{cookiecutter.email}}>"]
channels = ["https://repo.prefix.dev/mojo-force", "conda-forge", "https://conda.modular.com/max"]
description = "{{cookiecutter.project_short_description}}"
name = "{{cookiecutter.project_slug}}"
platforms = ["osx-arm64", "linux-64"]
version = "{{cookiecutter.version}}"


[tasks]
test = "mojo test.mojo"
build = "rattler-build build -r src -c https://repo.prefix.dev/mojo-force -c https://conda.modular.com/max -c conda-forge --skip-existing=all"
publish = { cmd = "bash scripts/publish.sh", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }

[dependencies]
max = ">=24.5.0,<25"
python = ">=3.8,==3.12"